# Generated by Django 4.1 on 2022-08-28 12:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("sensor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensor",
            name="sensor_id",
            field=models.CharField(
                blank=True, default=uuid.uuid4, max_length=100, unique=True
            ),
        ),
    ]
