# Generated by Django 4.1 on 2022-08-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensor", "0002_alter_sensor_sensor_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(max_length=200)),
                ("value", models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="sensor",
            name="sensor_id",
        ),
    ]
