# Generated by Django 4.1 on 2022-08-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensor", "0003_data_remove_sensor_sensor_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="date",
            field=models.CharField(max_length=200),
        ),
    ]
