# Generated by Django 4.1 on 2022-08-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensor", "0004_alter_data_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="data",
            name="sensor",
            field=models.CharField(default="Main Bearing Temperature", max_length=200),
            preserve_default=False,
        ),
    ]
